{
 "title": "PHP-FPM Multi Pool",
 "description": "PHP-FPM aggregated data for multiple pools.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(phpfpm_total_processes,instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "Pool", "label": "Pool", "query": { "query": "label_values(phpfpm_up,pool)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(phpfpm_up{instance=~\"^$Host$\", pool=~\"$Pool$\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "phpfpm_start_since{instance=~\"^$Host$\", pool=~\"$Pool\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pool) (phpfpm_active_processes{instance=~\"^$Host$\", pool=~\"$Pool$\"}) / sum by (pool) ( phpfpm_max_active_processes{instance=~\"^$Host$\", pool=~\"$Pool$\"})",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "PHP FPM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "The total number of accepted connections.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (rate(phpfpm_accepted_connections{instance=~\"^$Host$\", pool=~\"$Pool$\"} [$Interval]))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "timeseries",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (rate(phpfpm_slow_requests{instance=~\"^$Host$\", pool=~\"$Pool$\"} [$Interval]))",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Active processes",
   "type": "timeseries",
   "description": "The number of processes that are currently processing requests.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{instance=~\"^$Host$\", pool=~\"$Pool$\"}) by ( pool )",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Idle processes",
   "type": "timeseries",
   "description": "The number of processes that are currently idle (waiting for requests).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (phpfpm_idle_processes{instance=~\"^$Host$\", pool=~\"$Pool$\"})",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (phpfpm_max_children_reached{instance=~\"^$Host$\", pool=~\"$Pool$\"} )",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Max active processes",
   "type": "timeseries",
   "description": "The maximum number of concurrently active processes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (phpfpm_max_active_processes{instance=~\"^$Host$\", pool=~\"$Pool$\"})",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "timeseries",
   "description": "The number of requests (backlog) currently waiting for a free process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (rate(phpfpm_listen_queue{instance=~\"^$Host$\", pool=~\"$Pool$\"} [$Interval]))",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "Listen Queue Length",
   "type": "timeseries",
   "description": "The maximum allowed size of the listen queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (rate(phpfpm_listen_queue_length{instance=~\"^$Host$\", pool=~\"$Pool$\"} [$Interval]))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  { "title": "PHP FPM Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Memory usage (average)",
   "type": "timeseries",
   "description": "The maximum amount of memory consumed by the last request.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "avg(phpfpm_process_last_request_memory{instance=~\"^$Host$\", pool=~\"$Pool\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "CPU usage (average)",
   "type": "timeseries",
   "description": "Last CPU Request / Request Duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(phpfpm_process_last_request_cpu{instance=~\"^$Host$\", pool=~\"$Pool\"} / phpfpm_process_request_duration) by (pool) ",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Requests per process",
   "type": "timeseries",
   "description": "The total number of requests served.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg(phpfpm_process_requests{instance=~\"^$Host$\", pool=~\"$Pool\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "timeseries",
   "description": "Time used by the last request done (idle state) or the current request (all other states).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(phpfpm_process_request_duration{instance=~\"^$Host$\", pool=~\"$Pool\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{instance=~\"^$Host$\", pool=~\"$Pool\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(phpfpm_process_state{instance=~\"^$Host$\", pool=~\"$Pool\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}