route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack_notifications'

receivers:
- name: 'slack_notifications'
  slack_configs:
  - api_url: $SLACK_API_URL
    channel: '#alerts'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
