global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/rest/of/your/url'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack_notifications'

receivers:
- name: 'slack_notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
