global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - "rules.yml"
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php_fpm_exporter:9253']

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'elastic'
    static_configs:
      - targets: ['elastic_exporter:9114']

  - job_name: 'varnish'
    static_configs:
      - targets: ['varnish:9131']
