#!/bin/bash

set -e

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE USER IF NOT EXISTS '$MYSQLD_EXPORTER_USER'@'%' IDENTIFIED BY '$MYSQLD_EXPORTER_PASSWORD';
    GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '$MYSQLD_EXPORTER_USER'@'%';
    FLUSH PRIVILEGES;
EOSQL

exec "$@"
